### ISSUE TITLE
git credentials are not set in jenkins

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-launcher/launcher-planning#144]
I saw below errors in Jenkins log

<img width="1659" alt="screen shot 2018-03-28 at 11 49 30 am" src="https://user-images.githubusercontent.com/5129024/38072411-bbd6d4ec-3343-11e8-88a4-e63f96379b28.png">

**Comment by edewit** [comment]
fixed by https://github.com/fabric8-launcher/launcher-backend/pull/234

**Comment by ravsa** [comment]
I have just encountered this issue again
logs:
```log
Started by remote host kubernetes with note: Triggered by the change to the ConfigMap
[Wed Apr 04 17:01:47 UTC 2018] Starting organization scan...
[Wed Apr 04 17:01:47 UTC 2018] Updating actions...
Looking up details of loop-org...
ERROR: [Wed Apr 04 17:01:50 UTC 2018] Could not refresh actions for navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@1d8d03d
java.io.FileNotFoundException: https://api.github.com/users/loop-org
    at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
    at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
    at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
    at org.kohsuke.github.Requester.parse(Requester.java:612)
    at org.kohsuke.github.Requester.parse(Requester.java:594)
    at org.kohsuke.github.Requester._to(Requester.java:272)
Caused: org.kohsuke.github.GHFileNotFoundException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
    at org.kohsuke.github.Requester.handleApiError(Requester.java:686)
    at org.kohsuke.github.Requester._to(Requester.java:293)
    at org.kohsuke.github.Requester.to(Requester.java:234)
    at org.kohsuke.github.GitHub.getUser(GitHub.java:398)
    at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.retrieveActions(GitHubSCMNavigator.java:1160)
    at jenkins.scm.api.SCMNavigator.fetchActions(SCMNavigator.java:315)
    at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:410)
    at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
    at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
    at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:911)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:429)
[Wed Apr 04 17:01:50 UTC 2018] Consulting GitHub Organization
ERROR: [Wed Apr 04 17:01:50 UTC 2018] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@1d8d03d
hudson.AbortException: Invalid scan credentials ravsa/****** (cd-github) to connect to https://api.github.com, skipping
    at org.jenkinsci.plugins.github_branch_source.Connector.checkConnectionValidity(Connector.java:435)
    at org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator.visitSources(GitHubSCMNavigator.java:897)
    at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:459)
    at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:276)
    at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
    at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:911)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:429)
[Wed Apr 04 17:01:50 UTC 2018] Finished organization scan. Scan took 2.8 sec
FATAL: Invalid scan credentials ravsa/****** (cd-github) to connect to https://api.github.com, skipping
Finished: FAILURE
Page generated: Apr 4, 2018 5:02:35 PM UTCJenkins ver. 2.93
```

**Comment by gastaldi** [comment]
https://api.github.com/users/loop-org? Is that a valid user ID?

**Comment by gastaldi** [comment]
Hm apparently it is, weird

**Comment by gastaldi** [comment]
@ravsa Can you debug locally this line and confirm that it has the correct information: https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/impl/OsioJenkinsClientImpl.java#L56?

**Comment by gastaldi** [comment]
I have a feeling that https://github.com/fabric8-launcher/launcher-backend/blob/master/addons/osio-addon/src/main/java/io/fabric8/launcher/osio/client/impl/OsioJenkinsClientImpl.java#L37 may be injecting the wrong `IdentityProvider`. 

In this case, the fix is simple (just adding an `@Application(OSIO)` qualifier to that method parameter). Can you test that?

**Comment by edewit** [comment]
can you try and remove the `cd-github` so that it gets recreated? Maybe it got out of sync somehow?
