### ISSUE TITLE
Backend Node container won't start

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#186]
Environment: Minishift, using template install pulled ~18:00 Eastern time Friday.

Steps to repro:

1) Frontend: React
2) Backend Runtime: Node
3) Capabilities: All, DB using Postgres

```

git version 2.9.3
--
  | Using Node.js version: v11.0.0
  | Environment:
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Running as user uid=1000480000(default) gid=0(root) groups=0(root),1000480000
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@6.4.1
  | npm info using node@v11.0.0
  | > node-react-postgres@1.0.0 start /opt/app-root/src
  | > node .
  | npm info lifecycle node-react-postgres@1.0.0~prestart: node-react-postgres@1.0.0
  | npm info lifecycle node-react-postgres@1.0.0~start: node-react-postgres@1.0.0
  | internal/modules/cjs/loader.js:589
  | throw err;
  | ^
  | Error: Cannot find module '/opt/app-root/src'
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:513:25)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
  | at startup (internal/bootstrap/node.js:303:19)
  | at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
  | npm info lifecycle node-react-postgres@1.0.0~start: Failed to exec start script
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! node-react-postgres@1.0.0 start: `node .`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the node-react-postgres@1.0.0 start script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  | npm timing npm Completed in 1044ms
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /opt/app-root/src/.npm/_logs/2018-12-07T23_01_10_527Z-debug.log

```

**Comment by quintesse** [comment]
Fixed by https://github.com/fabric8-launcher/launcher-creator-backend/pull/109
