### ISSUE TITLE
Cannot import when using no Keycloak

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-planning#229]
![screenshot2](https://user-images.githubusercontent.com/199891/57207153-606dd180-6f99-11e9-80c8-13a04fd9dcc9.png)

Instructions to reproduce:

1) Install Launcher on Minishift via launcher-operator install instructions
2) Configure for import https://github.com/ALRubinger/rot13-backend
3) Launch

**Comment by ALRubinger** [comment]
Please have a loop ASAP @edewit and @quintesse?  Observed in latest version since Friday.  Thank you!

**Comment by gastaldi** [comment]
@ALRubinger what is the `launcher-backend` image version used? What happens if you change to `latest`?

**Comment by ALRubinger** [comment]
Yep, it's on `fabric8/launcher-backend:latest`

**Comment by gastaldi** [comment]
Mind pasting the logs from the launcher-backend pod?

**Comment by gastaldi** [comment]
is launcher-frontend also in `latest`?

**Comment by ALRubinger** [comment]
```

2019-05-06 04:51:26,798 WARNING [io.fab.lau.web.end.launch] (executor-thread-1) Projectile LauncherCreateProjectile{id=ee6b4c54-e137-49ca-9819-80a588275ebc, startOfStep=0, projectLocation=/tmp/projectDir4763271165545531955/flowing-stew, booster=null, openShiftProjectName=flowing-stew, gitRepositoryName=null, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launcher (https://developers.redhat.com/launch )} failed to launch. Time Elapsed: 00:00:00.600: java.lang.IllegalStateException: Could not find required env var or sys prop LAUNCHER_KEYCLOAK_URL
--
  | at io.fabric8.launcher.base.EnvironmentSupport.getRequiredEnvVarOrSysProp(EnvironmentSupport.java:110)
  | at io.fabric8.launcher.base.EnvironmentEnum.valueRequired(EnvironmentEnum.java:27)
  | at io.fabric8.launcher.core.impl.identity.KeycloakParameters.getUrl(KeycloakParameters.java:23)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters.getUrlInitialize(ImmutableKeycloakParameters.java:117)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters.access$300(ImmutableKeycloakParameters.java:23)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters$InitShim.getUrl(ImmutableKeycloakParameters.java:65)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters.<init>(ImmutableKeycloakParameters.java:36)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters.<init>(ImmutableKeycloakParameters.java:23)
  | at io.fabric8.launcher.core.impl.identity.ImmutableKeycloakParameters$Builder.build(ImmutableKeycloakParameters.java:316)
  | at io.fabric8.launcher.core.impl.producers.KeycloakParametersProducer.produceKeycloakParameters(KeycloakParametersProducer.java:18)
  | at io.fabric8.launcher.core.impl.producers.KeycloakParametersProducer_ProducerMethod_produceKeycloakParameters_d07d5f68484061fcf91952c048a9a9ada34bcf26_Bean.create(Unknown Source)
  | at io.fabric8.launcher.core.impl.producers.KeycloakParametersProducer_ProducerMethod_produceKeycloakParameters_d07d5f68484061fcf91952c048a9a9ada34bcf26_Bean.create(Unknown Source)
  | at io.quarkus.arc.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:86)
  | at io.quarkus.arc.AbstractSharedContext.lambda$new$0(AbstractSharedContext.java:33)
  | at io.quarkus.arc.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:115)
  | at io.quarkus.arc.LazyValue.get(LazyValue.java:42)
  | at io.quarkus.arc.ComputingCache.getValue(ComputingCache.java:57)
  | at io.quarkus.arc.AbstractSharedContext.get(AbstractSharedContext.java:39)
  | at io.fabric8.launcher.core.impl.producers.KeycloakParametersProducer_ProducerMethod_produceKeycloakParameters_d07d5f68484061fcf91952c048a9a9ada34bcf26_ClientProxy.delegate(Unknown Source)
  | at io.fabric8.launcher.core.impl.producers.KeycloakParametersProducer_ProducerMethod_produceKeycloakParameters_d07d5f68484061fcf91952c048a9a9ada34bcf26_ClientProxy.buildTokenUrl(Unknown Source)
  | at io.fabric8.launcher.core.impl.identity.KeycloakIdentityProvider.getIdentity(KeycloakIdentityProvider.java:76)
  | at io.fabric8.launcher.core.impl.identity.KeycloakIdentityProvider_ClientProxy.getIdentity(Unknown Source)
  | at io.fabric8.launcher.web.producers.IdentityProviderProducer_ProducerMethod_getIdentityProvider_d74e10f3e77cdfad6eb43a6eaed2ef12c93db482_ClientProxy.getIdentity(Unknown Source)
  | at io.fabric8.launcher.web.producers.GitServiceProducer.lambda$getGitService$1(GitServiceProducer.java:70)
  | at java.util.Optional.orElseGet(Optional.java:267)
  | at io.fabric8.launcher.web.producers.GitServiceProducer.getGitService(GitServiceProducer.java:70)
  | at io.fabric8.launcher.web.producers.GitServiceProducer_ProducerMethod_getGitService_62ab16e218ff64d3257a0d97ca89cda27a2c66de_Bean.create(Unknown Source)
  | at io.fabric8.launcher.web.producers.GitServiceProducer_ProducerMethod_getGitService_62ab16e218ff64d3257a0d97ca89cda27a2c66de_Bean.create(Unknown Source)
  | at io.quarkus.arc.RequestContext.get(RequestContext.java:79)
  | at io.fabric8.launcher.web.producers.GitServiceProducer_ProducerMethod_getGitService_62ab16e218ff64d3257a0d97ca89cda27a2c66de_ClientProxy.delegate(Unknown Source)
  | at io.fabric8.launcher.web.producers.GitServiceProducer_ProducerMethod_getGitService_62ab16e218ff64d3257a0d97ca89cda27a2c66de_ClientProxy.getProvider(Unknown Source)
  | at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:148)
  | at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.configureBuildPipeline(OpenShiftSteps.java:86)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:113)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:38)
  | at io.fabric8.launcher.web.endpoints.AbstractLaunchEndpoint.doLaunch(AbstractLaunchEndpoint.java:46)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint.uploadZip(LaunchEndpoint.java:136)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint_Subclass.uploadZip$$superaccessor3(Unknown Source)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint_Subclass$$function$$23.apply(Unknown Source)
  | at io.quarkus.arc.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:157)
  | at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:177)
  | at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:67)
  | at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:29)
  | at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
  | at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
  | at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
  | at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint_Subclass.uploadZip(Unknown Source)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint_ClientProxy.uploadZip(Unknown Source)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
  | at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
  | at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
  | at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
  | at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
  | at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:568)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:442)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:396)
  | at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:341)
  | at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
  | at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
  | at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:341)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
  | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
  | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
  | at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
  | at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
  | at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:234)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
  | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
  | at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.CorsFilter.doFilter(CorsFilter.java:49)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.gzip.GZipFilter.doFilter(GZipFilter.java:42)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
  | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
  | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:437)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
  | at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
  | at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
  | at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
  | at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
  | at java.lang.Thread.run(Thread.java:748)
  | at org.jboss.threads.JBossThread.run(JBossThread.java:479)


```

**Comment by gastaldi** [comment]
Just as I suspected. The `X-Git-Authorization` header is not sent thus the backend fails (because it uses that value to calculate the Provider name). I'll push a quick fix to the launcher-backend, 1 min
